from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _
from djblets.forms.fields import ConditionsField
from reviewboard.integrations.forms import IntegrationConfigForm
from reviewboard.reviews.conditions import ReviewRequestConditionChoices


class SkypeIntegrationConfigForm(IntegrationConfigForm):
    """Form for configuring Skype.

    This allows an administrator to set up a Skype configuration for sending
    messages to a given Skype WebHook URL based on the specified conditions.
    """

    conditions = ConditionsField(ReviewRequestConditionChoices,
                                 label=_('Conditions'))

    webhook_url = forms.CharField(
        label=_('Webhook URL'),
        required=True,
        help_text=_('Your unique Skype webhook URL generated by Skype Bot. '
                    'This can be found by you instantiating a new '
                    'conversation with the Skype Bot.'),
        widget=forms.TextInput(attrs={
            'size': 80,
        }))

    class Meta:
        fieldsets = (
            ('What To Post', {
                'description': _(
                    'You can choose which review requests would be posted by '
                    'choosing the repositories and groups to match against.'
                ),
                'fields': ('conditions',),
            }),
            ('Where To Post', {
                'description': _(
                    'To start, add the bot and start a new conversation on '
                    'Skype. You can then provide the unique URL generated '
                    'by the bot and pasted it in the "Webhook URL" section '
                    'below. The notification will be sent to the same '
                    'conversation that you initially started with the bot.'
                ),
                'fields': ('webhook_url',),
                'classes': ('wide',)
            }),
        )
